from sqlalchemy import create_engine, Column, String, Table
from sqlalchemy.orm import declarative_base, sessionmaker
import os
from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./fastapi_edx.db")

engine = create_engine(DATABASE_URL, connect_args={"check_same_thread": False})
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()

class UserLink(Base):
    __tablename__ = "user_links"
    link_id = Column(String, primary_key=True, index=True)
    email = Column(String, unique=True, index=True)

class UserToken(Base):
    __tablename__ = "user_tokens"
    email = Column(String, primary_key=True, index=True)
    access_token = Column(String)
    # Stores the password generated by this service for re-login to create sessions
    password = Column(String)

Base.metadata.create_all(bind=engine)
